import type { Metadata } from "next";
import Navbar from "../components/Navbar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        <Navbar/>
        <main className="mt-10">
            {children}
        </main>

    </div>




  );
}
